stages:
  - build
  - deploy

variables:
  IMAGE_NAME: gcr.io/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - echo "Logging in to Google Cloud Registry"
  - echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  - gcloud auth configure-docker

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $IMAGE_NAME .

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Pushing Docker image to Google Container Registry"
    - docker push $IMAGE_NAME
